apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-sts
spec:
  type: ClusterIP
  selector:
    app: nginx-sts
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
