version: '3.8'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./api:/app
    command: node server.js
    ports:
      - "3000:3000"

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: senha123
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
